### ISSUE TITLE
Augmentations only showing Cyberlimb options in latest build

### ISSUE THREAD

**Issue by Steve-Andrew-Lynch** [HeyOmae/Omae2.1#13]
There are no other augmentations selectable on the demo page. Below is all that is displayed.

![image](https://user-images.githubusercontent.com/3802682/33113579-e7b41de4-cf0d-11e7-854e-80c83a6de337.png)

**Comment by dethstrobe** [comment]
Not really an issue, just that the rest of the augmentations are not complete yet.
