### ISSUE TITLE
Weapon & Cybernetics Mods do not export

### ISSUE THREAD

**Issue by cheat117** [HeyOmae/Omae2.1#15]
When a user is customizing weapons and cybernetics and attempt to export the character to reddit, the markdown does not include those customizations.

Example of Exported Character:

# [Character Name] – [Player Name]

##Priority

Metatype | Attributes | Mag/Res | Skills | Resources
--------|----------|-------|------|---------
D | B | E | C | A

##Personal Details

**Name/Alias:** [Insert name]

**Metatype:** human

Street Cred | Notoriety | Public Awareness
-----------|---------|----------------
0 | 0 | 0

Karma | Total Karma
-----------|---------
0 | 0

##Attributes

Bod | Agi | Rea | Str | Wil | Log | Int | Cha | Edg | Mag | Ess
---|---|---|---|---|---|---|---|---|---|---
5 | 6 | 5 | 4 | 3 | 1 | 2 | 2 | 2 | – | 4.4

###Limits

Physical | Mental | Social
--------|------|------
6 | 3 | 3

##Qualities

Name | Category | Ref
----|------|---
Restricted Gear | Positive | RF p149
Restricted Gear II | Positive | RF p149
Friends in High Places | Positive | RF p147
Sensei | Positive | RF p149
Catlike | Positive | SR5 p72
Code of Honor | Negative | SR5 p79

##Magic/Resonance

**Type:** mundane

###Spells/Powers

			

##Skills

###Active

Name | Rating | Attribute | Spec | DP
----|------|---------|----|--
Sneaking | 3 | 6 | – | 9 
Locksmith | 4 | 6 | – | 10 
Heavy Weapons | 6 | 6 | – | 12 
Perception | 5 | 2 | – | 7 
Pilot Ground Craft | 3 | 5 | – | 8 
Blades | 6 | 6 | – | 12 
Clubs | 2 | 6 | – | 8 
Unarmed Combat | 2 | 6 | – | 8 
Demolitions | 3 | 1 | – | 4 

##Street Gear

### weapons

Name | Acc | Dam | AP | Reach/RC | Ref
----|------|-----|----|----------|--
Grapple Gun | 3 | 7S | -2 | 0 | SR5 p449,
Ares Thunderstruck Gauss Rifle | 7 | 15P | -8 | 0 | RG p45,
Throwing Knife | Physical | (STR+1)P | -1 | 0 | SR5 p424,
Throwing Knife | Physical | (STR+1)P | -1 | 0 | SR5 p424,
Throwing Knife | Physical | (STR+1)P | -1 | 0 | SR5 p424,
Throwing Knife | Physical | (STR+1)P | -1 | 0 | SR5 p424,
Vibro Sword | 6 | (STR+4)P | -2 | 1 | SASS p31

### Vehicles

Name | Rating | Ref
-----|--------|--
Shiawase Motors Shuriken | N/A | SAG p44

### ID/Credsticks

Name | Rating | Ref
-----|--------|--
Fake SIN | 4 | SR5 p442,
Fake SIN | 4 | SR5 p442,
Fake License | 4 | SR5 p443,
Fake License | 4 | SR5 p443

### armors

Name | Armor | Capacity | Ref
----|--------|----------|--
Full Body Armor | 15 | undefined/15 | SR5 p437

### Commlinks

Name | Rating | Ref
-----|--------|--
Pulse Wave | N/A | DT p17

### Explosives

Name | Rating | Ref
-----|--------|--
Detonating Cord, Low Yield (meter) | 3 | RG p193,
Detonating Cord, Low Yield (meter) | 3 | RG p193,
Dynamite | 1 | RG p190

### Survival Gear

Name | Rating | Ref
-----|--------|--
Survival Kit | N/A | SR5 p449

### Ammunition

Name | Rating | Ref
-----|--------|--
Ammo: Assault Cannon | N/A | SR5 p434,
Ammo: Assault Cannon | N/A | SR5 p434,
Ammo: Assault Cannon | N/A | SR5 p434,
Ammo: Assault Cannon | N/A | SR5 p434,
Ammo: Assault Cannon | N/A | SR5 p434,
Ammo: Assault Cannon | N/A | SR5 p434,
Ammo: Assault Cannon | N/A | SR5 p434,
Ammo: Assault Cannon | N/A | SR5 p434,
Ammo: Assault Cannon | N/A | SR5 p434,
Ammo: Assault Cannon | N/A | SR5 p434,
Ammo: Assault Cannon | N/A | SR5 p434,
Throwing Knife | N/A | SR5 p424,
Throwing Knife | N/A | SR5 p424,
Throwing Knife | N/A | SR5 p424,
Throwing Knife | N/A | SR5 p424,
Ammo: Stick-n-Shock | N/A | SR5 p434,
Ammo: Stick-n-Shock | N/A | SR5 p434,
Ammo: Stick-n-Shock | N/A | SR5 p434,
Ammo: Stick-n-Shock | N/A | SR5 p434,
Ammo: Stick-n-Shock | N/A | SR5 p434,
Ammo: Stick-n-Shock | N/A | SR5 p434

### augmentations

Name | Rating | Ref
-----|--------|--
Cyberears | N/A | SR5 p453,
Cybereyes Basic System | N/A | SR5 p453,
Smartlink | N/A | SR5 p453,
Thermographic Vision | N/A | SR5 p453,
Vision Enhancement | N/A | SR5 p453

### cyberlimbs

Name | Rating | Ref
-----|--------|--
Synthetic Full Arm | N/A | SR5 p456
			

Character page has Enhanced Strength rating 3 on synth full arm.

**Comment by dethstrobe** [comment]
This is something that I'll work on after I finish up drone modding
