### ISSUE TITLE
Investigate updating dependencies

### ISSUE THREAD

**Issue by apathy-dude** [HeyOmae/Omae2.1#2]
Ran npm install and got following warning messages:

```
npm WARN deprecated isparta-instrumenter-loader@1.0.1: isparta-instrumenter-loader is deprecated. Please use isparta-loader instead
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
```

**Comment by BenSower** [comment]
This can probably be fixed by updating the parent packages. 
At the moment, the following packages are outdated:

```
 normalize.css                   ^3.0.3  →         ^4.2.0 
 babel-eslint              ^5.0.0-beta9  →         ^6.1.2 
 copyfiles                       ^0.2.1  →         ^1.0.0 
 css-loader                     ^0.23.0  →        ^0.25.0 
 eslint                          ^1.2.1  →         ^3.5.0 
 eslint-plugin-react             ^3.3.0  →         ^6.3.0 
 file-loader                     ^0.8.4  →         ^0.9.0 
 glob                            ^6.0.0  →         ^7.1.0 
 karma                          ^0.13.9  →         ^1.3.0 
 karma-coverage                  ^0.5.3  →         ^1.1.1 
 karma-mocha                     ^0.2.0  →         ^1.1.1 
 karma-mocha-reporter            ^1.1.1  →         ^2.2.0 
 karma-phantomjs-launcher        ^0.2.1  →         ^1.0.2 
 mocha                           ^2.2.5  →         ^3.0.2 
 phantomjs                      ^1.9.18  →         ^2.1.7 
 postcss-loader                  ^0.8.0  →        ^0.13.0 
 react-hot-loader                ^1.2.9  →  ^3.0.0-beta.4 
 sass-loader                     ^3.1.2  →         ^4.0.2 
```
(I used the VERY useful https://www.npmjs.com/package/npm-check-updates to create this list)

The most pressing one is probably "tough-cookie", due to the ReDos vuln which appears to be a dependency of both node-sass and phantomjs
```
ben@slim:~/Desktop/Dev/repos/Omae2.1-master$ npm ls tough-cookie
omae2@2.1.4 /home/ben/Desktop/Dev/repos/Omae2.1-master
├─┬ node-sass@3.10.0
│ └─┬ request@2.75.0
│   └── tough-cookie@2.3.1 
└─┬ phantomjs@1.9.20
  └─┬ request@2.67.0
    └── tough-cookie@2.2.2 
```

isparta-instrumenter-loader is just plain deprecated and can probably be directly exchanged for isparta-loader. 
to-iso-string, jade and minimatch are also just dependencies of other packages.

Also, lodash is referenced in both dev- as well as regular dependencies.

I don't have time right now, but I will try to update all packages on the weekend.

**Comment by BenSower** [comment]
To check if any packages are outdated, you can use the npm package "ncu",
which will display all outdated packages.

Thomas Brown <notifications@github.com> schrieb am Fr., 9. Sep. 2016, 15:06:

**Comment by BenSower** [comment]
I created a PR for some updates: https://github.com/HeyOmae/Omae2.1/pull/8

**Comment by dethstrobe** [comment]
Thanks a ton Ben, that was something I kept putting on the back burner.

**Comment by dethstrobe** [comment]
I guess, I shouldn't close this until you've given the OK on all the dependencies.

**Comment by BenSower** [comment]
No problem, I was doing the same thing at work anyways (about 24 packages there...), so the few here were not a big thing ;-).

I will try to update the rest of the packages on the weekend and then we can close the ticket.

**Comment by dethstrobe** [comment]
I was able to update all the dependencies, and even upgrade the project to webpack 2, and the newest version of react and react hot loader. I haven't noticed anything terribly broken, other then my linter yelling at me, which I'll be fixing over the next few weeks, or days if I'm really quick about it.
