### ISSUE TITLE
Search filter

### ISSUE THREAD

**Issue by apathy-dude** [HeyOmae/Omae2.1#3]
Maybe I missed it, but a way to filter data from the pop-outs (qualities, skills, weapons, etc;) would be great improvement.  Being able to filter by book or name would be great, something like: https://www.npmjs.com/package/react-autocomplete could be useful.

**Comment by dethstrobe** [comment]
I also thought about that too. I'll see about actually starting work on that functionality.

**Comment by dethstrobe** [comment]
I realized why I dropped this off my priority list, most browsers have search options now and would kind of fill a similar niche to a filter, which is to basically find data. With that said, I still think I'm going to try implementing this as I think it'll be an interesting thought experiment.

**Comment by BenSower** [comment]
Some autocompletion would probably nice, so that the user already sees the
filtered results while typing. There are some good frameworks out there for
that.

William Johnson <notifications@github.com> schrieb am Fr., 23. Sep. 2016,
04:58:

**Comment by dethstrobe** [comment]
Well, this took longer then expected, but I was able to do it. Also, created a nice component to handle making filterable tables and display tables. I'm pretty happy with it.
